// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYIR8fp0kkIwxxVP50wK8F9R1jrl_0ak',
    appId: '1:481360520591:web:0a8703e2a68e15c9bf17fa',
    messagingSenderId: '481360520591',
    projectId: 'tubesabp2022-pintrst-kw',
    authDomain: 'tubesabp2022-pintrst-kw.firebaseapp.com',
    storageBucket: 'tubesabp2022-pintrst-kw.appspot.com',
    measurementId: 'G-RYZ9LJ6S7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwA2KdOcEns_-acaWl1JKRfx13G-x9Go',
    appId: '1:481360520591:android:104dec7e323a455ebf17fa',
    messagingSenderId: '481360520591',
    projectId: 'tubesabp2022-pintrst-kw',
    storageBucket: 'tubesabp2022-pintrst-kw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfKIpxqc44613hls0pdM0ZAIDoboWvXDI',
    appId: '1:481360520591:ios:f4f3f7898487a8b6bf17fa',
    messagingSenderId: '481360520591',
    projectId: 'tubesabp2022-pintrst-kw',
    storageBucket: 'tubesabp2022-pintrst-kw.appspot.com',
    iosClientId: '481360520591-cv0uqvaqn46qdllvf5mmossqu6gk5f68.apps.googleusercontent.com',
    iosBundleId: 'com.example.pintrstKw',
  );

  
}
